services:
  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: |
        ui = false
        storage "file" { path = "/vault/data" }
        listener "tcp" {
          address = "0.0.0.0:8200"
          tls_disable = true
        }
    volumes:
      - vault-data:/vault/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vault.rule=Host(`vault.voikyrioh.fr`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.tls.certresolver=cloudflare"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
      - "traefik.http.routers.vault.middlewares=secure-headers@file"

volumes:
  vault-data:

networks:
  proxy:
    external: true
