services:
  postgres:
    image: postgres:17-alpine
    container_name: shared_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    name: postgres

volumes:
  postgres-data:
